# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/asd/workspaceCPP/cpp-boost

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/asd/workspaceCPP/cpp-boost

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asd/workspaceCPP/cpp-boost/CMakeFiles /home/asd/workspaceCPP/cpp-boost//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asd/workspaceCPP/cpp-boost/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app1_boost

# Build rule for target.
app1_boost: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app1_boost
.PHONY : app1_boost

# fast build rule for target.
app1_boost/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1_boost.dir/build.make CMakeFiles/app1_boost.dir/build
.PHONY : app1_boost/fast

#=============================================================================
# Target rules for targets named app2

# Build rule for target.
app2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app2
.PHONY : app2

# fast build rule for target.
app2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/build
.PHONY : app2/fast

#=============================================================================
# Target rules for targets named app_NRVO

# Build rule for target.
app_NRVO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_NRVO
.PHONY : app_NRVO

# fast build rule for target.
app_NRVO/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_NRVO.dir/build.make CMakeFiles/app_NRVO.dir/build
.PHONY : app_NRVO/fast

#=============================================================================
# Target rules for targets named app_containers

# Build rule for target.
app_containers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_containers
.PHONY : app_containers

# fast build rule for target.
app_containers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_containers.dir/build.make CMakeFiles/app_containers.dir/build
.PHONY : app_containers/fast

app1_boost.o: app1_boost.cpp.o
.PHONY : app1_boost.o

# target to build an object file
app1_boost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1_boost.dir/build.make CMakeFiles/app1_boost.dir/app1_boost.cpp.o
.PHONY : app1_boost.cpp.o

app1_boost.i: app1_boost.cpp.i
.PHONY : app1_boost.i

# target to preprocess a source file
app1_boost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1_boost.dir/build.make CMakeFiles/app1_boost.dir/app1_boost.cpp.i
.PHONY : app1_boost.cpp.i

app1_boost.s: app1_boost.cpp.s
.PHONY : app1_boost.s

# target to generate assembly for a file
app1_boost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1_boost.dir/build.make CMakeFiles/app1_boost.dir/app1_boost.cpp.s
.PHONY : app1_boost.cpp.s

app2_boost.o: app2_boost.cpp.o
.PHONY : app2_boost.o

# target to build an object file
app2_boost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/app2_boost.cpp.o
.PHONY : app2_boost.cpp.o

app2_boost.i: app2_boost.cpp.i
.PHONY : app2_boost.i

# target to preprocess a source file
app2_boost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/app2_boost.cpp.i
.PHONY : app2_boost.cpp.i

app2_boost.s: app2_boost.cpp.s
.PHONY : app2_boost.s

# target to generate assembly for a file
app2_boost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/app2_boost.cpp.s
.PHONY : app2_boost.cpp.s

app_NRVO.o: app_NRVO.cpp.o
.PHONY : app_NRVO.o

# target to build an object file
app_NRVO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_NRVO.dir/build.make CMakeFiles/app_NRVO.dir/app_NRVO.cpp.o
.PHONY : app_NRVO.cpp.o

app_NRVO.i: app_NRVO.cpp.i
.PHONY : app_NRVO.i

# target to preprocess a source file
app_NRVO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_NRVO.dir/build.make CMakeFiles/app_NRVO.dir/app_NRVO.cpp.i
.PHONY : app_NRVO.cpp.i

app_NRVO.s: app_NRVO.cpp.s
.PHONY : app_NRVO.s

# target to generate assembly for a file
app_NRVO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_NRVO.dir/build.make CMakeFiles/app_NRVO.dir/app_NRVO.cpp.s
.PHONY : app_NRVO.cpp.s

app_containers.o: app_containers.cpp.o
.PHONY : app_containers.o

# target to build an object file
app_containers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_containers.dir/build.make CMakeFiles/app_containers.dir/app_containers.cpp.o
.PHONY : app_containers.cpp.o

app_containers.i: app_containers.cpp.i
.PHONY : app_containers.i

# target to preprocess a source file
app_containers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_containers.dir/build.make CMakeFiles/app_containers.dir/app_containers.cpp.i
.PHONY : app_containers.cpp.i

app_containers.s: app_containers.cpp.s
.PHONY : app_containers.s

# target to generate assembly for a file
app_containers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_containers.dir/build.make CMakeFiles/app_containers.dir/app_containers.cpp.s
.PHONY : app_containers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app1_boost"
	@echo "... app2"
	@echo "... app_NRVO"
	@echo "... app_containers"
	@echo "... app1_boost.o"
	@echo "... app1_boost.i"
	@echo "... app1_boost.s"
	@echo "... app2_boost.o"
	@echo "... app2_boost.i"
	@echo "... app2_boost.s"
	@echo "... app_NRVO.o"
	@echo "... app_NRVO.i"
	@echo "... app_NRVO.s"
	@echo "... app_containers.o"
	@echo "... app_containers.i"
	@echo "... app_containers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

